version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./binds/nginx:/etc/nginx
      - ./binds/ssl:/etc/ssl/private