version: '2'
services:
  # frontend_app:
  #   image: nginx
  #   volumes:
  #     - ./ui:/usr/share/nginx/html
  #   ports:
  #     - "80"

  frontend_app:
    image: nginx
    volumes:
      - ./ui:/usr/share/nginx/html
    ports:
      - "80"

  # https://stackoverflow.com/a/65213529/9034699
  elasticsearch_app:
    # build: ./elasticsearch/
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    # container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      # - output.mount=/usr/share/elasticsearch/data/backups
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/iodata:/usr/share/elasticsearch/iodata
    ports:
      - 9200:9200



  backend_app:
    # image: nginx
    build: ./api/
    environment:
      - APP_PORT=8000
      - GUNICORN_CMD_ARGS=--workers=4 --log-level=debug --bind=0.0.0.0:8000
      - ELASTICSEARCH_URL=http://youtube_downloader_elasticsearch_app_1
      - ELASTICSEARCH_PORT=9200
    # volumes:
    #   - ./api/app:/youtube_downloader/app/
    ports:
      - 4444:8000