version: '2'
services:
  frontend_app:
    image: nginx
    volumes:
      - ./ui:/usr/share/nginx/html
    ports:
      - "80"

  # https://stackoverflow.com/a/65213529/9034699
  elasticsearch_app:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    # container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "80"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200



  backend_app:
    image: nginx
    volumes:
      - ./api:/usr/share/nginx/html
    ports:
      - "80"