version: '2'
services:
  frontend_app:
    image: nginx
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - "80"


  elasticsearch_app:
    image: nginx
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - "80"
      

  backend_app:
    image: nginx
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - "80"