version: '2'
services:
  proxy:
    build: ./
    networks:
      - youtube_downloader
      # - example2
    ports:
      - 80:80
      - 443:443

networks:
  youtube_downloader:
    external:
      name: youtube_downloader_default
  # example2:
  #   external:
  #     name: example2_default